### ISSUE TITLE
What is this project?

### ISSUE THREAD

**Issue by m3thm4th** [fcitx/mozc#66]
How is this fork different from the [original](https://github.com/google/mozc)?

The Readme is identical, if this project is different from the original, there should be a brief description in the Readme explaining the difference. Is it just a mirror?

I came here because NixOS offers both [ibus-engines.mozc](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/by-name/mo/mozc/package.nix#L99) and [fcitx5-mozc](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/tools/inputmethods/fcitx5/fcitx5-mozc.nix#L123) packages, but the latter is a little bit outdated.

**Comment by wengxt** [comment]
You'll know what's new by diff master & fcitx branch.

As for how nix os provides the package, it's up to nix os package maintainer to update it.

**Comment by wengxt** [comment]
@m3thm4th 
I don't want to touch any file that presents in the original repo. It may affect the automated merge process.

**Comment by wengxt** [comment]
it's a patched version of mozc that contains fcitx support.

**Comment by wengxt** [comment]
https://github.com/fcitx/mozc/tree/fcitx/src/unix

**Comment by wengxt** [comment]
It doesn't add any new feature to mozc as an engine, but just some glue code between mozc & fcitx.

**Comment by eagleoflqj** [comment]
Issue tracker is not used for such questions. You may find better answer in chatgpt, e.g. https://chatgpt.com/share/671adc22-9994-8008-94c7-37263949c249

**Comment by wengxt** [comment]
Application on linux can't talk to mozc directly, it talks to a input method server (fcitx, ibus, etc), which are also commonly referred as input method framework. In most case, you can only use one IMF at a time on your desktop.

Why it's called framework, it's because they acts as bridge between the input method engine and application.

If you want answer about comparison between fcitx and other frameworks, you should do some web search, or try it out yourself.

Using the same engine on different framework should gives you similar experience. There might be some minor difference, but usually not affect main functionality.
